# Generated by Django 4.1.7 on 2023-02-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Email подписка',
                'verbose_name_plural': 'Email подписки',
            },
        ),
        migrations.CreateModel(
            name='InfoPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=255, verbose_name='Страница к которой относится информация')),
                ('information', models.TextField(verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Страница информации',
                'verbose_name_plural': 'Страницы информации',
            },
        ),
    ]
