# Generated by Django 4.1.7 on 2023-02-22 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=255, verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.AlterField(
            model_name='infopages',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pagecategory', verbose_name='Страница'),
        ),
    ]
