# Generated by Django 4.1.7 on 2023-02-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pagecategory_alter_infopages_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('work_experience', models.CharField(max_length=255, verbose_name='Опыт работы')),
                ('from_age', models.CharField(max_length=3, verbose_name='Возраст от')),
                ('to_age', models.CharField(max_length=3, verbose_name='Возраст до')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('skills', models.CharField(max_length=255, verbose_name='Навыки')),
                ('education', models.TextField(verbose_name='Образование')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
