# Generated by Django 4.1.7 on 2023-02-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='from_salary',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Зарплата от'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='to_salary',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Зарплата до'),
        ),
    ]
