# Generated by Django 4.1.7 on 2023-02-27 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_vacancies_from_salary_vacancies_to_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в виде +998(12)1234567', regex='^\\+998\\(\\d{2}\\)\\d{7}$')], verbose_name='Номер телефона')),
                ('problem', models.TextField(verbose_name='Описание проблемы')),
            ],
            options={
                'verbose_name': 'Помощь',
                'verbose_name_plural': 'Помощи',
            },
        ),
    ]
